[fields]
data_directory = "~/Dropbox/circulation/data/4vortices"
data_index = 1
N = [256, 256]  # resolution: can be 2D or 3D
# N = [256, 256, 1]

[circulation]
epsilon_velocity = 1e-10  # for "correcting" velocity near vortices

# 2D slice of 3D dataset to be studied.
# Zeroes are transformed to ":" in Julia. There should be exactly two of them.
# Only used if input dataset is 3D (i.e. if fields.N has length 3).
slice_3d = [0, 0, 1]

[physics]
c = 1.0
nxi = 1.5
