[fields]
# Path to data. Note that environment variables are allowed.
data_directory = "$HOME/Dropbox/circulation/data/tangle/256/fields"
data_index = 1       # timestep
N = [256, 256, 256]  # resolution: can be 2D or 3D
L_2pi = [1, 1, 1]    # domain size in multiples of 2π (default is [1, 1, 1])

# If true, load incompressible regularised velocity field ("VI{x,y,z}_d.*.dat")
# instead of wave function field ("Psi*.dat").
load_velocity = false

# data_directory = "~/Work/simulation_data/GP/circulation/tangle/1024"
# data_index = 100
# N = [1024, 1024, 1024]

# Refinement factor of the wave-function field ψ (default is 1).
# Must be a positive integer. In particular, downsampling is not allowed.
# If greater than 1, the input field is resampled into a finer grid with
# `resampling_factor` times the original points.
# The resampling is done by zero-padding ψ in Fourier space.
# Note that the loop sizes defined in circulation.loops refer to the original
# grid resolution, and not the resampled one.
resampling_factor = 1  # only useful for circulation!

[physics]
c = 1.0
nxi = 1.5

[output]
# Statistics are saved in HDF5 format.
statistics = "tangle_256.h5"

[circulation]
# Compute circulation statistics?
enabled = true

# Maximum number of slices per orientation to analyse.
# If 0 (default), all available slices are analysed.
max_slices = 8

# For "correcting" velocity near vortices (0 for no correction).
# epsilon_velocity = 1e-10
epsilon_velocity = 0

    [circulation.loops]
    # Type of selection of integer loop size:
    #   - "list": array or range of sizes (see `sizes` option).
    #   - "log":  logarithmically distributed sizes (see `log_base` option).
    selection_type = "log"

    # List of integer loop sizes if selection_type = "list".
    # The three following examples are accepted.
    # sizes = 4                   # a. single loop size
    # sizes = "2:2:10"            # b. range of sizes
    # sizes = [1, 2, 4, 8, 16]    # c. list of sizes
    sizes = [1, 2, 4, 8, 16, 32, 64]

    # Logarithmic base if selection_type = "log".
    # Sizes will be of the form `round(log_base^n)` for `n >= 0` integer.
    # Repeated values will be removed.
    log_base = 1.4

    [circulation.statistics]
    # If fields.resampling_factor > 1, accumulate statistics in the resampled
    # (finer) grid instead of the original grid.
    # This leads to more statistics (which may or may not be redundant...), and
    # takes more time. Default is false.
    compute_in_resampled_grid = false

    [circulation.statistics.moments]
    p_max = 10  # maximum exponent (should be even)

    # Number of fractional exponents to compute in 0 < p ≤ 1.
    # If this is 10, the exponents in 0.1:0.1:1 will be considered.
    # Default is 0 (no fractional exponents).
    # N_fractional = 10

    [circulation.statistics.histogram]
    num_bin_edges = 4000  # number of bin edges; should be even so that the
                          # zero value falls inside a bin
    max_kappa = 30.5  # max value in histogram (in units of kappa)


# Velocity increment statistics.
# Parameters are mostly the same as for the circulation.
[increments]
enabled = false
max_slices = 8
epsilon_velocity = 0

    [increments.spatial_offsets]
    selection_type = "log"
    # sizes = [1, 2, 4, 8, 16, 32, 64]
    log_base = 1.4

    [increments.statistics]
    compute_in_resampled_grid = false

    [increments.statistics.moments]
    p_max = 10
    N_fractional = 0

    [increments.statistics.histogram]
    num_bin_edges = 4000
    max_c = 10.0  # max velocity in histogram (in units of speed of sound)
