name = "Circulation"
uuid = "f9745a5e-b5bf-4554-ab79-8fb660046134"
authors = ["Juan Ignacio Polanco <jipolanc@gmail.com>"]
version = "0.1.0"

[deps]
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
